### ISSUE TITLE
Add documentation/helpers for class based views

### ISSUE THREAD

**Issue by barakalon** [plangrid/flask-rebar#11]
Using classes for view functions in Flask is a common patten (see [flask-restful](https://flask-restful.readthedocs.io/en/latest/) and [flask-restplus](https://github.com/noirbizarre/flask-restplus)).

Using classes is currently possible with Flask-Rebar, but we should add whatever is needed to make it really easy to do this.

**Comment by twosigmajab** [comment]
> Using classes is currently possible with Flask-Rebar

Was just wondering about this and: awesome, great to hear this is true!

> but we should add whatever is needed to make it really easy to do this.

I haven't tried this yet, but FWIW, it seems like it'd be valuable to include an example of this in the meantime, and I think the existing [todolist example](https://github.com/plangrid/flask-rebar/blob/master/examples/todo/todo.py) would be a great fit for this: Make a TodoApi class that subclasses [MethodView](http://flask.pocoo.org/docs/1.0/views/#method-views-for-apis), and move the current @registry.handle'd standalone functions `create_todo()`, `update_todo()`, etc. to be `post()`, `put()`, etc. methods of that subclass. What do you think?

**Comment by barakalon** [comment]
> it seems like it'd be valuable to include an example of this

I think an example is a great idea. It'll also force us to see if we need any extra functionality to support it better.

I would avoid changing the existing example and just add it as a second example - something like "class_based_views"

I know I've used flask-rebar for class based views, and I don't remember any caveats... but its been a while. If some helpers are warranted, I don't see any reason not to add them.

**Comment by twosigmajab** [comment]
Can this be closed as of #63 landing? (@barakalon ftw, thanks again!)
