### ISSUE TITLE
API docs are broken in Flask-Rebar docs

### ISSUE THREAD

**Issue by twosigmajab** [plangrid/flask-rebar#110]
https://flask-rebar.readthedocs.io/en/latest/api_reference.html currently shows nothing but section headings.

**Comment by RookieRick** [comment]
Yikes - nice catch; I'll see what's up

**Comment by RookieRick** [comment]
(note this isn't actually resolved - my PR wasn't quite aggressive enough..  stay tuned :) )

**Comment by RookieRick** [comment]
OK having corrected my initial misdiagnosis, this should be fixed now
