### ISSUE TITLE
Breaking changes between marshmallow 3.0.0rc6 and 3.0.0

### ISSUE THREAD

**Issue by RookieRick** [plangrid/flask-rebar#118]
In `setup.py` we currently pin to `marshmallow>=2.13,<4`.

As noted in comments on #43 this morning, the actual 3.0.0 release of Marshmallow introduces some breaking changes.  We had tested against 3.0.0rc5 in our TravisCI setup.  I just verified that 3.0.0rc6 also passes but rc7+ and the actual release of 3.0.0 do cause us to blow up.

This got conflated with a much less severe difference that I stumbled across between marshmallow 2.19 and 2.20 causing one of our tests to fail (but unlikely imho to cause any real issues) in an initially misguided and since closed PR I started that would have pinned to `<=2.19` 😓  Thanks @barakalon and @PratikPramanik for catching me on that one 😄 Ref #117 for a cleaner fix to that issue that doesn't mess with any pinned versions.

With the 2.19 vs 2.20 issue now handled in a more clean/compartmentalized fashion, the burning question for the next PR I need to make is: "do we consider it a breaking change if we change `setup.py` pin to `marshmallow>=2.13,<3`?"  I'm of a mind that this would be more like an "unbreaking change" because anyone who simply ran `pip install '.[dev]'` in a clean environment since yesterday when 3.0.0 was actually released would be in a broken state, which leads me to believe correct course of action here is:
1. Release a patch version that pins to `marshmallow>=2.13,<3` - potentially unbreaking anybody who broke due to 3.0.0 release of marshmallow and/or at least preventing new breakings, thereby buying us time to:
2. Actually go back and make things compatible with marshmallow 3.0.0 before:
3. re-pinning to `marshmallow>=2.13,<4` once we're satisfied that we can operate with 3.*

Thoughts? If nobody has any major heartburn with this approach I'll go ahead and get a patch released tomorrow to buy us that time to deal with 3.0.0 incompatibility

**Comment by Sytten** [comment]
This seems reasonable to me, it will give us a bit of breathing room and unblock users (me included). We should get that first merge ASAP.

**Comment by RookieRick** [comment]
OK, v1.9.1 should unbreak things in current state while we investigate what needs to be changed to get back to compat with marshmallow
