### ISSUE TITLE
Add support for multiple Authenticators

### ISSUE THREAD

**Issue by airstandley** [plangrid/flask-rebar#121]
Rebar has the ability to set a default_authenticator that is applied to all handlers in a registry.

It is a fairly common pattern to support multiple styles of authentication, for example one might allow a user to login and pass a session token, or instead allow a client to pass an api key.

I'm proposing we make it possible to define both the authenticator for a handler, and the default_authenticator as a list of Authenticators, and change the wrap_handler method so that if any of these Authenticators passes then the request is considered authenticated.

**Comment by airstandley** [comment]
Worth noting: I'm of the opinion that since list are ordered, that the first Authenticator to pass should short-circuit and none of the proceeding Authenticators would run.

**Comment by Sytten** [comment]
That's an interesting idea. Some comments:
- I faced a related issue when designing my auth0 authenticator, I had no way of saying that you either need to pass auth as an super_admin role OR org_admin role.
- One could argue that you can already do that with a custom authenticator that takes as argument as list of authenticators, we just have to write said authenticator. This has the advantage of not changing the public interface.

**Comment by airstandley** [comment]
> * One could argue that you can already do that with a custom authenticator that takes as argument as list of authenticators, we just have to write said authenticator. This has the advantage of not changing the public interface.

A completely valid approach and my initial plan.

We are making a conscious effort to improve our swagger specs though so it is highly desirable that that the swagger spec shows that there are multiple available `securitySchemes`, rather than a single complex one.
