### ISSUE TITLE
Integrate marshmallow-objects

### ISSUE THREAD

**Issue by Sytten** [plangrid/flask-rebar#131]
One annoying thing about marshmallow is the fast that you get a dictionary instead of an object with attributes (I am bit jealous of [pydantic](https://github.com/samuelcolvin/pydantic)). We started using [marshmallow-objects](https://github.com/SVilgelm/marshmallow-objects) in our project. Since we already define some custom schemas, it would be very valuable to either use this lib or make something similar. Especially since we are going toward a v2 with some breaking changes anyway.

**Comment by Sytten** [comment]
We might also want to switch to pydantic too, it's very good. FastAPI uses it extensively.

**Comment by barakalon** [comment]
+1

I'd also add, beyond just objects, we should have first class support for type annotated object.

After spending some time using type annotations, I wouldn't want to use a framework that doesn't support them.

**Comment by Sytten** [comment]
I did a small experiment:
```python
class TestSchema(Model):
    id = fields.Integer()

@registry.handles(rule="/test", method="POST", request_body_schema=TestSchema)
def post_test():
    body: TestSchema = get_validated_body()
    print(body.id)
    return "", 200
```

The problems I faced were:
- An error if I added `()` to `request_body_schema=TestSchema`
- An error with the compact of marshmallow V2 (the lib seems only compatible with V3)
- The typing of `get_validated_body` is set to dict

Otherwise it works!

**Comment by Sytten** [comment]
As we discuss a v2, we might want to consider using another framework too. Pydantic has been gaining a lot of tracking lately, but it's python 3.6+. @airstandley thoughts?

**Comment by airstandley** [comment]
Pydantic looks interesting, but I don't quite see the flexibility that Marshmallow has for customizing field behavior. 

I'd love to mess around with pydantic so it would be neat for Rebar to support it, but I would not want to use it to replace Marshmallow in existing apps.

**Comment by RookieRick** [comment]
Hey all - some clarifications on this one..  Is the proposal to _augment_ or _replace_ here?  I've been assuming _augment_ a la "you can provide us with either a vanilla marshmallow `Schema` _or_ a marshmallow-objects `Model` and Rebar will figure out what to do with it - but @Sytten mention of breaking changes makes me wonder if I misinterpreted intent.
Similarly I'm assuming if we want to support `Model` for request schemas we prob want to do same for response - haven't dug into any details yet but gut says that may be tricky (but doable).

**Comment by Sytten** [comment]
The only breaking change would be in the typing I believe. Though it might be best to keep it as dict and force a cast by the user?

**Comment by jaypz** [comment]
I'd like to :heavy_plus_sign::one:  exploring the idea of supporting pydantic :smiley:

**Comment by barakalon** [comment]
Just throwing this out there...

What if in addition to (or instead of) [marshmallow-objects](https://github.com/sv-tools/marshmallow-objects), we support dataclasses using [marshmallow_dataclass](https://github.com/lovasoa/marshmallow_dataclass)?

That'd be a lot of glue (dataclasses -> marshmallow-dataclass -> marshmallow -> rebar -> openapi)... but if it worked, it'd be pretty nifty.

@RookieRick

**Comment by RookieRick** [comment]
> Just throwing this out there...
> 
> What if in addition to (or instead of) [marshmallow-objects](https://github.com/sv-tools/marshmallow-objects), we support dataclasses using [marshmallow_dataclass](https://github.com/lovasoa/marshmallow_dataclass)?
> 
> That'd be a lot of glue (dataclasses -> marshmallow-dataclass -> marshmallow -> rebar -> openapi)... but if it worked, it'd be pretty nifty.
> 

Heh I did stumble across that one recently - generally speaking my philosophy is "the more the merrier" if we can build in support for popular `marshmallow` addons.  (Even merrier in my book if somebody already using it elsewhere has background knowledge and spare cycles to implement it, but regardless we could add it to the ever-growing Issues list and try to pick it off at some point! 😂 )
