### ISSUE TITLE
ResponseSchema is missing constructor parameters

### ISSUE THREAD

**Issue by Sytten** [plangrid/flask-rebar#137]
I often use the `many=True` for `Schema` in the returned body, but it's not possible with the `ResponseSchema` class because it doesn't implement a constructor.

**Comment by airstandley** [comment]
Hey Sytten,
  `ResponseSchema` does not need to implement it's own` __init__`, it will inherit `Schema`'s

You should be able to register handlers with many=True schemas:
```
@registry.handles(
   response_body_schema=ResponseSchema(many=True),
)
def my_handler():
     pass
```

Hope that helps!

**Comment by Sytten** [comment]
Hum yeah it must work because one of the parent doesn't have a constructor. Just pycharm complaining about it.

**Comment by RookieRick** [comment]
Hey, just doing some cleanup after being drawn away from Rebar for far too long ;)  Looks like this one is resolved; if not feel free to reopen

**Comment by Sytten** [comment]
Sure, its just annoying in pycharm but it works

**Comment by airstandley** [comment]
I will admit, that sounds pretty obnoxious.
