### ISSUE TITLE
How to use flask-marshmallow

### ISSUE THREAD

**Issue by stanep** [plangrid/flask-rebar#139]
Hi, thank you guys  for all good work, I have question , I am lazy :), I am testing flask-rebar and want to use flask-marshmallow
class UserSchema(ma.Schema):
    username = fields.Str()
    created_at = fields.DateTime()
    _links = ma.Hyperlinks({'collection': ma.URLFor("api/v1.get_users")})

This works as url, but fails to generate swagger doc, I am guessing you need to "register" URLFor and Hyperlinks , any ideas

**Comment by Sytten** [comment]
Hummmm The code to convert marshmallow to swagger is tightly coupled to the official marshmallow lib. All the converters are found in this file https://github.com/plangrid/flask-rebar/blob/master/flask_rebar/swagger_generation/marshmallow_to_swagger.py
You will need to write some custom converters for your field types and add them to the registry.

**Comment by airstandley** [comment]
Hey stanep,
 Thanks for the question.

Sytten is right and you will need to register some custom converters.
https://flask-rebar.readthedocs.io/en/latest/quickstart/swagger_generation.html#custom-marshmallow-types details how to add customer converters for custom marshmallow fields (or ones from a third party library in this case).

Hope that helps.
