### ISSUE TITLE
Allow hidden API

### ISSUE THREAD

**Issue by Sytten** [plangrid/flask-rebar#141]
It would be great to be able to hide some APIs if they are not meant to be public. A parameter in the handles decorator would do the trick.

**Comment by airstandley** [comment]
If we did this, I think we should also add a parameter to the generators. 
I'm not a huge fan of 'private' APIs in general, but I know that I would definitely want to be able to generate full documentation (including 'private' endpoints) for internal consumption.

**Comment by mjanes** [comment]
Closed with https://github.com/plangrid/flask-rebar/pull/191
