### ISSUE TITLE
Git flow for v2

### ISSUE THREAD

**Issue by Sytten** [plangrid/flask-rebar#164]
How do we want to do the git flow for v2?
I suggest we start a V2 branch and backports for the features that need it

**Comment by RookieRick** [comment]
I think we may want to do similar but actually have a V1 branch (which only gets limited backported updates/bugfixes) so master by default remains the "current" version

**Comment by RookieRick** [comment]
Threw this out for discussion on Discord, but of course people can feel free to comment here as well..  My envisioned workflow here is something like:

1. For now we continue to work in our single "master" branch, up until the point we've knocked out the Issues tagged "V2"
2. Once we've knocked out issues tagged "V2" we will
   2.a. release v2.0.0 obvs, which would include any "non-V2" issues addressed between now and then, but more importantly
   2.b create a new branch "releases/V1.x" (or similar name)
3 For future Issues, a PR to master would only update V2.x so would require a separate PR to backport to V1.x - we would want to use this judiciously, backporting bug fixes (and arguably, only "critical" bug fixes) and not feature updates unless somebody is feeling extra-generous with their time :)

**Comment by RookieRick** [comment]
I went ahead and created the `releases/V1` branch off of `master` - it has the same branch protection rules so should require PRs to update, etc.
We will use that branch to backport any critical fixes to 1.x - otherwise new feature stuff added to `master` will contribute to 2.0 release at this point.
