### ISSUE TITLE
pin werkzeug <1.0

### ISSUE THREAD

**Issue by joeb1415** [plangrid/flask-rebar#166]
Werkzeug, a sub-dependency of flask, released a major version 1.0.0 today:
https://pypi.org/project/Werkzeug/#history

This is breaking a few things on some of our builds. Looks like Flask does not pin a major version of werkzeug:
https://github.com/pallets/flask/blob/master/setup.py#L56

There is some discussion in the flask discord about it but no issues or discussion of a resolution yet
https://discordapp.com/channels/531221516914917387/531221866145251366

Can we pin `werkzeug^=0.16` in rebar for now?

**Comment by davidism** [comment]
It looks like this is only an issue in tests, you're using Flask-Testing which has a fix submitted but not merged or released yet. It looks like your use of Flask-Testing can be replaced with a few pytest fixtures, or pytest-flask, there's nothing complicated going on.
