### ISSUE TITLE
Use application/json rather than application/vnd.plangrid+json

### ISSUE THREAD

**Issue by twosigmajab** [plangrid/flask-rebar#17]
`SwaggerV2Generator` produces `application/vnd.plangrid+json` by default:

https://github.com/plangrid/flask-rebar/blob/fcdd3b016a9b218dcaa53aa70467e2e2f0832d8d/flask_rebar/swagger_generation/swagger_generator.py#L278

This seemed unusual and after looking a bit I wasn't able to find any clues as to why this doesn't use `application/json` instead. Any interest in switching to `application/json`?

Thanks for your consideration and for maintaining flask-rebar. After looking at several options (flask-apispec, flasgger, flask-restplus), this seems like the best.

**Comment by barakalon** [comment]
Ah, this is purely an accident! flask-rebar started as an internal package, and this must've just been left in there.

I'll put up a fix

**Comment by twosigmajab** [comment]
Thanks for the quick fix! I'll follow #19. Just out of curiosity, it looks like you're waiting for someone to review before you can merge, but are not sure who to ask? From https://github.com/plangrid/flask-rebar/graphs/contributors it looks like you wrote most of this library, but GitHub isn't showing any "owner", "collaborator", or even "contributor" badge by your comments... wat?

**Comment by barakalon** [comment]
Ok, https://github.com/plangrid/flask-rebar/pull/19 is merged. 
It will make it to pypi on the next release. If the change is urgent, I'll look to @juliusiv to make the release (and to mark this issue as resolved)

**Comment by juliusiv** [comment]
@twosigmajab I just released this as version 1.0.6. Let me know if there are any problems. In the meantime, I'm going to close this issue as resolved.
