### ISSUE TITLE
Support OpenAPI Spec version 3?

### ISSUE THREAD

**Issue by twosigmajab** [plangrid/flask-rebar#18]
It looks like flask-rebar provides a `SwaggerV2Generator` but not a `SwaggerV3Generator` (or similar). OpenAPI Spec v3 was released last year (see https://github.com/OAI/OpenAPI-Specification/releases). Is there any interest in adding support for this to flask-rebar?

**Comment by barakalon** [comment]
There's definitely _interest_.

OpenAPI v3 is still relatively new, and community tooling hasn't quite caught up yet (e.g. https://github.com/swagger-api/swagger-codegen). PlanGrid chose to stick with v2 for this reason, and there hasn't been a call to create SwaggerV3Generator yet - this would be that first call!

Is support for v3 a requirement for you? Or are you just curious about goals?

Also... I can take a swing at SwaggerV3Generator, but it might take me some time. Any interest in contributing?

**Comment by twosigmajab** [comment]
We are currently using version 2, but in the coming months intend to evaluate updating to 3 along with looking at https://github.com/OpenAPITools/openapi-generator, the Swagger Codegen fork that also supports OAI 3. Good to see that contributing this to Flask-Rebar would be considered, will definitely keep that in mind.

**Comment by juliusiv** [comment]
+1 for support for this. Swagger2's lack of allowing null values would be nice. We've noticed we need to dumb down schemas a bit because of that.

**Comment by barakalon** [comment]
Yeah, this is inevitable and increasingly important.

I've been meaning to hop on this, but haven't had time.

If anyone else wants to handle this change... 😬

**Comment by joeb1415** [comment]
Any updates on this issue? I am considering working on this as a hackweek project next week, curious if anyone has put any more thought or time into it in the past few months. 

In addition to the null values Julius mentioned, I am excited to add support for OneOf as well, as we discussed a while back here: https://github.com/plangrid/flask-rebar/pull/48#issuecomment-443805956.

**Comment by barakalon** [comment]
I haven’t put in any additional thought/time. 

This would be a fantastic contribution! I tried my best to write the existing code in preparation for this, but who knows what will happen. 

I’m happy to lend some initial thoughts, maybe a walkthrough the relevant code, if you’re interested.

**Comment by Sytten** [comment]
We can close this one @RookieRick

**Comment by RookieRick** [comment]
🎉
