### ISSUE TITLE
mistake in docs

### ISSUE THREAD

**Issue by twosigmajab** [plangrid/flask-rebar#22]
https://flask-rebar.readthedocs.io/en/latest/quickstart/swagger_generation.html#default-response demonstrates overriding the default swagger generator, but mistakenly documents passing `swagger_generator` to the `Rebar` initializer (which does not accept this argument):
```python
rebar = Rebar(swagger_generator=generator)
```
It should instead document passing this to the Registry initializer, which does accept this argument.

**Comment by barakalon** [comment]
Thanks for the issue!
Here's a fix: https://github.com/plangrid/flask-rebar/pull/23

**Comment by barakalon** [comment]
@juliusiv this issue can be closed
