### ISSUE TITLE
Support for Flask v2

### ISSUE THREAD

**Issue by jab** [plangrid/flask-rebar#232]
Flask v2 is due to come out in the next couple weeks, see https://palletsprojects.com/blog/end-python2-prereleases/

This issue tracks adding basic compatibility to Rebar with Flask v2 (making sure all current tests pass in CI and existing Rebar functionality works as expected). Taking advantage of Flask v2-specific features can be tracked in dedicated issues (e.g. #231).

**Comment by dekim24** [comment]
working on this here https://github.com/plangrid/flask-rebar/pull/239

**Comment by dekim24** [comment]
I merged the PR - can someone help bump version number / release the client? (cc @RookieRick or anyone who is an admin)
