### ISSUE TITLE
Swagger: How to add title and description?

### ISSUE THREAD

**Issue by bloomen** [plangrid/flask-rebar#280]
Hello! First of all thank you for this awesome framework!!
I was able to integrate flask rebar into my project and view the swagger UI. However, I didn't find a way to adjust title, description and version of my project. How would I do that? And similarly I would like add descriptions to each route and field. How is that done?
Thanks!

**Comment by gtmanfred** [comment]
Flask-rebar picks up the doc strings from the handler functions and uses that as the description in the swagger file. There is actually potentially some change to this coming, if you check out #256 

As for title and version of the project, I believe you can pass that to the swagger generator you specify on your registry when you create it, https://github.com/plangrid/flask-rebar/blob/master/flask_rebar/rebar.py#L707
(This is not required for generic use, but it is if you want to customize it)
https://github.com/plangrid/flask-rebar/blob/master/flask_rebar/swagger_generation/swagger_generator_v3.py#L56-L58

And you configure this on every handler registry.
