### ISSUE TITLE
update changelog

### ISSUE THREAD

**Issue by twosigmajab** [plangrid/flask-rebar#33]
Looks like info for the last few patch releases is missing from https://github.com/plangrid/flask-rebar/releases and https://github.com/plangrid/flask-rebar/blob/master/CHANGELOG.rst.

**Comment by barakalon** [comment]
Ah, yeah. We need to get better at this.
I'd love to base both these release messages _and_ the CHANGELOG off of git history, using something like https://github.com/conventional-changelog/conventional-changelog

@juliusiv , is PlanGrid using any tools for maintaining CHANGELOGs? I seem to remember @goosemo introducing something....

**Comment by juliusiv** [comment]
Done with https://github.com/plangrid/flask-rebar/pull/56
