### ISSUE TITLE
Prepare for Marshmallow 3

### ISSUE THREAD

**Issue by twosigmajab** [plangrid/flask-rebar#37]
https://github.com/plangrid/flask-rebar/blob/master/setup.py#L19 specifies `marshmallow>=2.13`. Right now this is picking up Marshmallow 2, but as soon as Marshmallow 3 final comes out, this will start picking up v3, which has several backwards-incompatible changes:

https://marshmallow.readthedocs.io/en/3.0/changelog.html

Are any updates necessary before then?

**Comment by barakalon** [comment]
Woof, I've running the tests with 3.0.0b20... and there are some pretty nasty breaking changes coming through.

We've got a couple of options:
1) modify the current dependency to be `marshmallow>=2.13,<3` and release a new major version of flask-rebar that depends on `marshmallow>=3`. This is probably the least convenient for consumers of this package, but will lead to much simpler code.
2) support both major version of marshmallow in flask-rebar. I'll keep hacking away at this... but it's not going down easy.

**Comment by twosigmajab** [comment]
@barakalon Thanks for looking into this! Doing a new release with just the marshmallow dep pinned to `marshmallow>=2.13,<3` that users can upgrade to now seems like it should be done asap, no? That way users can upgrade now to make sure they don't one day start pulling in an incompatible marshmallow version and their apps suddenly start breaking.

**Comment by twosigmajab** [comment]
(and in general, each dependency should be pinned within its semver-compatible range, in case there are others in the same boat)

**Comment by barakalon** [comment]
I put up a PR that free the need to add `marshmallow>=2.13,<3` to requirements.txt.

It's a little messy, so I'm going to sleep on it and come back to it tomorrow.

> and in general, each dependency should be pinned within its semver-compatible range

Yep, agreed.

**Comment by twosigmajab** [comment]
> I put up a PR that free the need to add `marshmallow>=2.13,<3` to requirements.txt.

Nice! Looks like it's #43 -- just left some comments there. Also, don't forget you'd still want to add the semver upper bound like `marshmallow>=2.13,<4` (as we just agreed) until compatibility with some future marshmallow v4 is proven.

And re requirements.txt see #44.

**Comment by twosigmajab** [comment]
Just noticed @sloria's "environs" is also [only specifying "marhsmallow>=2.7.0"](https://github.com/sloria/environs/blob/master/setup.py#L5), but advertises a ["marshallow 3" status badge](https://github.com/sloria/environs#environs-simplified-environment-variable-parsing), interesting. @sloria, curious if you're taking a similar approach to #43 for maintaining marshmallow 2 + 3 compatibility.

**Comment by sloria** [comment]
@twosigmajab Yeah, environs (and all of the projects in [marshmallow-code](https://github.com/marshmallow-code)) are compatible with marshmallow 2 and 3. We use a similar approach, checking the marshmallow major version as necessary.

Great to see that you're working on marshmallow 3 support. Hoping to have a final release soon!

> A stable release of marshmallow 3 is on the horizon! marshmallow 3 is already a massive improvement on version 2, and we're focused on cutting the final release as soon as we can. I estimate that we'll have the a release candidate within the next month. You can follow our progress here: https://github.com/marshmallow-code/marshmallow/milestones .

From https://opencollective.com/marshmallow/updates/how-your-donations-are-used

**Comment by barakalon** [comment]
I believe this issue can be closed 🎉

**Comment by RookieRick** [comment]
Re-opening this one as the history may be helpful -  the final release of 3.0.0 is out and there are some new changes there that we'll need to address.

**Comment by Sytten** [comment]
Now that marshmallow 3 is more stable and available, we should revisit. I would be glad to get rid of the `RequestSchema` vs just a normal `Schema`.

**Comment by barakalon** [comment]
Might be worth considering a new major version of flask-rebar. Maintaining backwards compatibility across multiple versions of marshmallow, flask, _and_ openapi is proving to be pretty tricky.

**Comment by Sytten** [comment]
Anyone have time to take a stab at it @RookieRick  @barakalon? I really want to use the new features of marshmallow :S

**Comment by barakalon** [comment]
@Sytten Unfortunately, I don't have time right now 😕

**Comment by RookieRick** [comment]
@Sytten As much as I hate reverting to this answer..  I'm going to try to look into this more "soon" :)  Currently have another perfect storm of impending deadlines plus a combo of scheduled vacation plus some unscheduled absence time over the past few weeks.  So for the moment I'm in kind of the same boat as Barak but will definitely be trying to claw my way back to Rebar ASAP

**Comment by airstandley** [comment]
I'm pro cutting Marshmallow 2 support in v2.0.  
@RookieRick adding it to the version checklist.

Any objections?

**Comment by RookieRick** [comment]
I was about to say "oh but can we support both" but given that we're doing a major version release that does seem like a good point to cut the cord on older versions of dependencies.  This looks like it may have some useful info for this endeavor:  https://marshmallow.readthedocs.io/en/stable/upgrading.html

**Comment by Sytten** [comment]
The problem I face currently with my codebase is that we use a beta version of marshmallow 3 because that's the limit set by the requirements of flask. So the doc from 2.0 is not quite right nor is the doc from 3.0... It is annoying to say the least.

**Comment by mjanes** [comment]
Believe flask-rebar is fully on Marshmallow 3 after https://github.com/plangrid/flask-rebar/pull/195

**Comment by Sytten** [comment]
It used to not work with the latest version of marshmallow (post-beta), was that fixed?

**Comment by airstandley** [comment]
> It used to not work with the latest version of marshmallow (post-beta), was that fixed?

Hey Sytten, the head of `master` (the commit referenced above) should be fixed and now work (exclusively) with the latest version of marshmallow. However there is not yet a released version.
