### ISSUE TITLE
move from requirements.txt to install_requires and extras_require in setup.py

### ISSUE THREAD

**Issue by twosigmajab** [plangrid/flask-rebar#44]
requirements.txt is meant to be used by applications, not libraries, and this is a library. Rebar should be using setup.py's `install_requires` as the single source of truth for always-required dependencies, and an `extras_require` field to set up additional sets of dependencies e.g. for testing. (So you'd do e.g. `pip install -e .[test]` to get the additional test dependencies.)

Here's an example:
- https://github.com/jab/bidict/blob/master/setup.py#L117
- https://github.com/jab/bidict/blob/master/.travis.yml#L31

**Comment by barakalon** [comment]
> requirements.txt is meant to be used by applications, not libraries, and this is a library. 

Agreed!

> Rebar should be using setup.py's install_requires as the single source of truth for always-required dependencies

Agreed!

> and an extras_require field to set up additional sets of dependencies e.g. for testing. (So you'd do e.g. pip install -e .[test] to get the additional test dependencies.)

This one I'm not opposed to, but I'm still skeptical. 

From https://setuptools.readthedocs.io/en/latest/setuptools.html:

> A dictionary mapping names of “extras” (optional features of your project) to strings or lists of strings specifying what other distributions must be installed to support those features. See the section below on Declaring Dependencies for details and examples of the format of this argument.

What I've put in requirements.txt aren't _extra features_ of this library. Rather, they're what's required for development.

I could be missing a perspective, though. And for the most part, I'm open to whatever we think is best. I'd just rather avoid changing anything if its simply a different but equal convention.

**Comment by RookieRick** [comment]
Thanks again @retornam! 👍
