### ISSUE TITLE
Support for tags

### ISSUE THREAD

**Issue by twosigmajab** [plangrid/flask-rebar#52]
I don't see anything about tags in the docs, nor any signs of support from https://github.com/plangrid/flask-rebar/search?q=tags&type=Code

Is there support for tags, or if not would you want to add it?

Ref: https://swagger.io/docs/specification/2-0/grouping-operations-with-tags/

Thanks!

**Comment by twosigmajab** [comment]
Sounds good to me! Great you'd want it added too. Thanks!

**Comment by twosigmajab** [comment]
Hey @barakalon et al., happy new year!

Sorry I haven't had time to take a stab at this yet. Is this something anyone was thinking of working on anytime soon?

**Comment by barakalon** [comment]
@twosigmajab I was planning on picking this up when I get the chance - I've just been a bit MIA with holidays/vacation

And anyone of course should feel free to hop on it :)

**Comment by twosigmajab** [comment]
#55 landed a few weeks ago (whoo!) -> closing
