### ISSUE TITLE
Create a more complete example

### ISSUE THREAD

**Issue by Sytten** [plangrid/flask-rebar#62]
I just discovered `flask-rebar` and I think it could very well become the new standard for REST with flask. The documentation is very well made, but a more complete "real-life" example/template would help a lot to get started. I am creating one for my project that i could share, but I don't know all the best practices for the framework.
Keep up the good work, cheers!

**Comment by Sytten** [comment]
One issue I faced for example is when having separate controller files, the paths would not be registered properly when creating the app because the file was loaded after the `init_app`

**Comment by barakalon** [comment]
Hi @Sytten ! Thanks for the support.

Ah, yes. Import order can be tricky with the registry pattern. The trick that I usually see is:
(1) one module where rebar and its handler registries are instantiated
(2) handler module import that module
(3) the module that initializes the app imports all handler files

Roughly:

registry.py
```python
import flask_rebar

rebar = flask_rebar.Rebar()
registry = rebar.create_handler_registry()
```

foo_handler.py
```python
import .registry

@registry.handles("/foo")
def get_foo():
    ...
```

app.py
```python
from flask import Flask

from .registry import rebar
from .foo_handler import get_foo  # noqa

def create_app(name):
    app = Flask(name)
    rebar.init_app(app)
    return app
```

But you are correct - this deserves its own example! Similar to https://github.com/plangrid/flask-rebar/issues/11

**Comment by Sytten** [comment]
Thanks! Yes I figured it out eventually. If my team ends up choosing rebar, I will most certainly write a tutorial for it.
I am considering mixing it with https://github.com/justanr/marshmallow-annotations to generate Schema from dataclass and using the dataclass in the `post_load` to have a full object instead of a plain dict. Not sure how nicely it would play with the swagger generator though.

**Comment by barakalon** [comment]
I don't know much about https://github.com/justanr/marshmallow-annotations nor if it would work with flask-rebar out of the box, but flask-rebar _does_ support pluggable marshmallow-to-swagger converters: https://flask-rebar.readthedocs.io/en/latest/quickstart/swagger_generation.html#custom-marshmallow-types

**Comment by Sytten** [comment]
Interesting, I will check that in due time. Probably need to create a custom authenticator for cognito too eventually, I could probably share it as an extension. Feel free to close the issue or keep it open, I might ramble more thoughts as we go in our project :D
BTW Plangrid should really write a blog post on rebar, I didn't see any on the engineering blog. Could help the project if it goes top on HN.

**Comment by RookieRick** [comment]
Thanks @Sytten - I'm taking over maintenance of Flask-rebar here; will leave this one open for now as I'm a big fan of rambled thoughts :D  One of the things I'm doing is ensuring each open Issue has an assignee, for now will just assign this one to you (and will look forward to seeing what examples you build if you end up writing that tutorial!)

**Comment by Sytten** [comment]
Good to hear! We decided to go with rebar, so it's very likely that I will write something about it during the year. My next challenge is to integrate it with cognito authentication.

**Comment by Sytten** [comment]
Ok it has started, if you guys have time to proof read I would appreciate (english is not my native language :S): https://medium.com/@emilefugulin/creating-a-production-ready-python-rest-backend-with-flask-rebar-part-1-62f498d2f077

**Comment by RookieRick** [comment]
This looks really good so far!  Will have to figure out the best place(s) to link to it from our docs as I'm sure others will find this helpful when Flask-Rebar becomes the _de facto_ standard for Flask frameworks! :D

**Comment by twosigmajab** [comment]
OT but...

> BTW Plangrid should really write a blog post on rebar, I didn't see any on the engineering blog. Could help the project if it goes top on HN.

https://github.com/humiaozuzu/awesome-flask/pull/162

hope this helps spread the word!

**Comment by Sytten** [comment]
Good initiative @twosigmajab!
I will try to release my second article as soon as I find some time to finish it.
To gain some traction, we should also comment on flask-restplus and other abandoned frameworks to encourage people to check it.
Finishing OpenAPI 3.0 would help though :P

**Comment by RookieRick** [comment]
OMG you guys are the best :) <3
I still don't have a date-certain but OpenAPI 3.0 is very much on the radar now so .. .SOON! :D  (and for bonus points, I figured I'd write a PlanGrid blog post to "announce" it when it's done ;)

**Comment by Sytten** [comment]
Second part of the series is out: https://medium.com/@emilefugulin/creating-a-production-ready-python-rest-backend-with-flask-rebar-part-2-d6bcf4a5f0b2

**Comment by Sytten** [comment]
@RookieRick @barakalon Let me know what you guys think of it :)

**Comment by barakalon** [comment]
Love it!

I'm also happy to make comments on typos and other small things, if you care. I think Medium has a draft link? Or maybe thats only prior to publishing.

**Comment by RookieRick** [comment]
I started reading it and got pulled off on something else yesterday but looked pretty good so far!  I'll try to get back to it shortly.  Thanks again for putting this together btw!

**Comment by Sytten** [comment]
@barakalon Feel free to send a list, I think the draft link is disabled since its published.
@RookieRick My pleasure :)

**Comment by RookieRick** [comment]
Looks great - one suggestion:  I'd go back and add a link to part 2 at the end of part 1 to make it easy for people to follow through the series.

**Comment by twosigmajab** [comment]
(Anyone want to send a quick PR to https://github.com/apisyouwonthate/openapi.tools to get Flask-Rebar listed on https://openapi.tools?)
