### ISSUE TITLE
Cognito authenticator

### ISSUE THREAD

**Issue by Sytten** [plangrid/flask-rebar#72]
I created an authenticator for cognito, do you think that I should create a PR to merge it in Rebar or it should live it's in own package?
I want to battle test it a bit though before releasing since I am not sure of all the flows of cognito.

**Comment by barakalon** [comment]
Awesome!

From a purist perspective, I think it should live in its own package. From a practical perspective, I can understand wanting to avoid bootstrapping a python package that releases to PyPI, runs test on Travis, publishes documentation, etc. 

Here's some questions to help suss out if its reasonable to sneak it into flask-rebar itself:
**Does it bring in additional dependencies?** Flask-rebar tries to be lightweight, and I think it'd be a bummer if developers who didn't need the integration had to pull in something like `boto`.
**How much maintenance will it require?** If they lived in the same package, releases and versions would be coupled. Releasing a new major version of the integration would require releasing a major version of flask-rebar.
**What do sufficient tests require?** Does the plugin require integration tests with Incognito? That might be messy to shoehorn into flask-rebar tests.

**Comment by Sytten** [comment]
1. At the very least, it needs `requests` and `python-jose`. They are quite lightweight though. For performances, it is recommended to use something like `cryptography`.
2. I think the maintenance is low for the basic usage of verifying JWT tokens, if we want to handle other flows that might require more.
3. Currently only unit tests would be required if I bypass the expiration time checking for the tests.

I really don't mind that much creating my own package, it really depends if you want to go down the plugin way or not.

**Comment by barakalon** [comment]
I'd vote for the plugin way, especially if you don't mind 😬

**Comment by RookieRick** [comment]
Hi! I just realized I didn't have notifications turned on so just now seeing this.  It sounds like it's roughly agreed that a separate plugin is probably the cleanest approach here.  Sytten, I'll go ahead and "assign" this issue to you and make it your call if you would like to keep it open as a discussion medium as you move forward.  Thanks!!!

**Comment by Sytten** [comment]
I managed to finish the user flow with `access_token`. I will add the possibility to fetch info from the `id_token` soon and I will add an optional callback to fetch info about the user. I need to figure out I will do the machine-to-machine flow.

I also plan to incorporate some helpers for roles and organizations using custom attributes: https://aws.amazon.com/blogs/apn/managing-saas-identity-through-custom-attributes-and-amazon-cognito/

**Comment by Sytten** [comment]
Ok finally we switched to Auth0 and I just finished it: https://github.com/Sytten/flask-rebar-auth0

**Comment by barakalon** [comment]
Awesome! 

I added a section in the README for extensions: https://github.com/plangrid/flask-rebar/pull/76
