### ISSUE TITLE
better default for "host" of SwaggerV2Generator?

### ISSUE THREAD

**Issue by twosigmajab** [plangrid/flask-rebar#77]
`SwaggerV2Generator` currently defaults `host` to `"swag.com"`:
https://github.com/plangrid/flask-rebar/blob/4f8b41b940d6f054ef815b608285dc5ec69c41c5/flask_rebar/swagger_generation/swagger_generator.py#L336

Since the Flask-Rebar users I'm supporting all use Rebar's (awesome) [serverless generation](https://flask-rebar.readthedocs.io/en/latest/quickstart/swagger_generation.html#serverless-generation) feature to generate an OpenAPI spec build artifact for their APIs, they all end up with `host: swag.com` in their api.yml's. Since this spec file then goes on to become the input for Swagger-Codegen-generated e.g. TypeScript clients, the default `basePath` of the generated clients becomes `"https://swag.com"`. So users inevitably have to add the following boilerplate to get a working client integrated into their Flask-served UIs:
```typescript
import * as Client from "../../gensrc/client"
const Api = new Client.WhoamiApi({basePath: location.origin})
```
As with #61, I'm wondering if Rebar could be using a better default value for "host" that would reduce this boilerplate for users, or if anyone has any other recommendations here. Thanks!

**Comment by barakalon** [comment]
I think this is one of the inherent weaknesses of OpenAPI 2.0.
OpenAPI 3.0 has `servers`, which supports more sophisticated declarations here: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#server-object

**Comment by Sytten** [comment]
Diverging a bit, but I also support the OpenAPI 3.0 for the support of cookie authentication.

**Comment by RookieRick** [comment]
I think for V2, as far as I can see the "best" option is just to pass appropriate host to SwaggerV2Generator -- which only works if your devs know the host where it's going to run in advance, and remember to tell the generator, so not sure **_how_** helpful that is.  Seems like any default we include is going to be imperfect; but perhaps something like localhost would at least be better than pointing to swag.com and potentially generating unintended outbound traffic..to... an actual swag merchant? 🤣

**Comment by barakalon** [comment]
Haha maybe I have vested interested in [swag.com](https://swag.com)?

**Comment by RookieRick** [comment]
Should probably just default to localhost :)
