### ISSUE TITLE
Minor refactor: move USE_DEFAULT

### ISSUE THREAD

**Issue by RookieRick** [plangrid/flask-rebar#94]
`USE_DEFAULT` is defined in `flask_rebar.authenticators` but its usage has been expanded so it probably belongs in a more generic utility module

**Comment by retornam** [comment]
@RookieRick what are your thoughts on moving this into `utils` so it becomed 
``` from flask_rebar.utils import USE_DEFAULT``` or 
```from flask_rebar.utils.defaults import USE_DEFAULT```

**Comment by RookieRick** [comment]
Yeah I think having a `defaults` module in `utils` (even if it just contains that one dummy class for now) seems like a nice clean way to organize this
