### ISSUE TITLE
s/swagger/openapi where needed (e.g. create_handler_registry's "swagger_path" param, SwaggerV2Generator, etc.)

### ISSUE THREAD

**Issue by twosigmajab** [plangrid/flask-rebar#98]
The `swagger_path` param is used to set the location of the OpenAPI spec file. But since 1/1/2016, OpenAPI refers to the specification; Swagger refers to tooling around it (e.g. the Swagger UI). Would it make sense to rename this param? Something like `openapi_path` or just `spec_path`?

**Comment by barakalon** [comment]
I think we'd have to _add_ the parameter and deprecate the old one in order to maintain backwards compatibility, but I dig `spec_path` :+1:

**Comment by RookieRick** [comment]
In related research on #89 I came across this approach https://stackoverflow.com/a/49802489/977046 which I'll prob try out on that other one.  If it works well should make this pretty easy

**Comment by RookieRick** [comment]
https://github.com/plangrid/flask-rebar/blob/master/flask_rebar/utils/deprecation.py has been added and can be used (extend as needed) for this - huzzah!

**Comment by twosigmajab** [comment]
`swagger_path` isn't the only example in Rebar's public API where "swagger" is being used rather than "OpenAPI", e.g. we also have `SwaggerV2Generator` and `SwaggerV3Generator`.

I've retitled this ticket for a more general "s/swagger/openapi" pass through Rebar's APIs, and targeted this ticket at v2.0.

**Comment by Sytten** [comment]
I agree and we should also setup a github action to update the swagger ui when a new version comes out. It shouldn't too hard to do. We could switch to redoc too (which I prefer).

**Comment by twosigmajab** [comment]
@Sytten did you mean to leave this comment in #54? Seems more relevant over there. (But as long as we're chatting about this here, I think Redocly/redoc#53 would be a blocker for replacing Swagger UI with ReDoc (the Rebar users I support rely on those "Try it out" buttons all the time), though the look and feel of ReDoc is definitely prettier.)

**Comment by Sytten** [comment]
Right I didn't see this issue, we should do that for v2. I thought redoc had a try it out button :S

**Comment by RookieRick** [comment]
Done

**Comment by jab** [comment]
Not a big deal, but to fully address this issue, I think all the APIs in https://github.com/plangrid/flask-rebar/tree/master/flask_rebar/swagger_generation that refer to "swagger generation" should be renamed as well. ("spec generation", "OpenAPI spec generation", or some such.)
